version: '3.9'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: tsehayneshbiruh2
      POSTGRES_PASSWORD: tsehayteam
      POSTGRES_DB: Fithaber
    ports:
      - "5432:5432"  # Host 5434 -> Container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - equity-network

  # Backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3000"  # Host 3001 -> Container 3000
    command: node src/server.js 
    depends_on:
      - db
    env_file:
      - ./backend/.env 
    networks:
      - equity-network

  # Frontend
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - equity-network

# Named volumes
volumes:
  postgres_data:

# Network
networks:
  equity-network:
    driver: bridge
