version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5434:5433"  # Standard Postgres port
    environment:
      POSTGRES_USER: tsehayneshbiruh2
      POSTGRES_PASSWORD: tsehayteam
      POSTGRES_DB: Fithaber
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - equity-network

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    command: npx nodemon server.js
    depends_on:
      - db
    networks:
      - equity-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - equity-network

volumes:
  postgres_data:

networks:
  equity-network:
    driver: bridge
